# Generated by Django 3.2 on 2024-05-06 11:33

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(db_index=True, help_text='Введите год, который не превышает текущий.', validators=[reviews.validators.validate_year], verbose_name='Год выпуска'),
        ),
    ]
